/**
 * Songs that the band had never played live, according to KGLW.net
 *
 * Source: https://kglw.net/unplayed/1
 */
export const songsNeverPlayedLive = [
  "2.02 Killer Year",
  "9 TET",
  "A Brief History of Planet Earth",
  "A Journey To (S)Hell",
  "ABABCD",
  "Ain't It Funky Now",
  "Ain’t No Mountain High Enough",
  "Alluda Majaka",
  "Anamnesis",
  "Are You Gonna Be My Girl",
  "Back Door Man",
  "Bad Star",
  "Barefoot Desert",
  "Beyond the Sea",
  "BIT BIT BIT BIT BIT BIT BIT",
  "Black Hot Soup",
  "Blindness",
  "Blue Horse",
  "Blue Morpho",
  "Body Movin'",
  "Bone",
  "Boy on the Run",
  "Brassicas",
  "Butterfly 3000",
  "Can't Keep My Eyes Off Of You",
  "Can't Stop",
  "Candles",
  "Catching Smoke",
  "Cellophane (single version)",
  "Cold Cadaver",
  "Come On",
  "Cookies",
  "Cotton-Eyed Joe",
  "Cranes, Planes, Migraines",
  "Dawn of Eternal Night",
  "Demo No. 67",
  "Demo No. 79",
  "Depressed",
  "Down Under",
  "Down with a Sickness",
  "Dreams",
  "Drum Run",
  "Dusk To Dawn On Lygon Street",
  "Dust In the Wind",
  "Embryo",
  "España cañí",
  "Eucalyptus Noserun",
  "Evergreen",
  "Every Morning",
  "Everybody Needs Somebody To Love",
  "Evil Star",
  "Evilest Man",
  "Exploding Suns",
  "Fire",
  "Fishing For Fishies",
  "Flying Fishie",
  "Flying Microtonal Banana",
  "Fort Whipple",
  "Forty Six & 2",
  "Foxey Lady",
  "Frankenstein",
  "Freedom",
  "Fuck tha Police",
  "Gaia/Motor Spirit",
  "Garage Liddiard",
  "German Rock n' Rolle",
  "Get Low",
  "Gliese 710",
  "God May Not Be WIth Us",
  "Going Up the Country",
  "Gonna Make You Sweat (Everybody Dance Now)",
  "Good Riddance (Time of Your Life)",
  "Got My Mojo Working",
  "Guns & Horses",
  "Happy Birthday To You",
  "Happy Birthday, Lisa",
  "Hear My Eyes: Suspiria Rescoring",
  "Hell's Itch",
  "Hells Bells",
  "Hey Joe",
  "Hey Pachuco",
  "Homeless Man In Adidas",
  "I Am Dumb",
  "I Don’t Love You No More",
  "I Love L.A.",
  "I Say",
  "I'd Rather Go Blind",
  "I'll Be Gone",
  "I'm Bored",
  "I'm Sleepin' In",
  "If You Want My Love",
  "In Da Club",
  "Incredible",
  "Infinite Rise",
  "Intergalactic",
  "Isn't She Lovely",
  "It's a Long Way to the Top (If You Wanna Rock 'N' Roll)",
  "Jam",
  "Kelebek",
  "Killing in the Name",
  "Lean Woman Blues",
  "Life/Death",
  "Little Wing",
  "Lost Woods",
  "Lukey's Brain",
  "Machine Gun",
  "Marble",
  "Mariposa",
  "Master of the Universe",
  "Midnight Rambler",
  "Mornin",
  "Moses",
  "MTV",
  "Music To Burn Money To",
  "Music To Die To",
  "Music To Eat Bananas To",
  "Music To Eat Pond Scum To",
  "Music To Kill Bad People To",
  "Music To Think Existentially To",
  "My Babe",
  "My Generation",
  "Mycelium",
  "N.G.R.I. (Bloodstain)",
  "Nein",
  "No Body",
  "Nonagon Intro Theme",
  "Not Enough Time... Land",
  "Nothing Left To Hide (King Gizzard Remix)",
  "Nutbush City Limits",
  "Ocean Deep",
  "OCS",
  "Oddments",
  "One",
  "One, Two, Freddy's Coming For You",
  "Out of Space",
  "Paper Mâché",
  "Parking",
  "Party Potential",
  "Pipe-Dream",
  "Plasma",
  "Play That Funky Music",
  "Pop",
  "Praise You",
  "Pride and Joy",
  "Pump Up the Jam",
  "Purple Haze",
  "Quarantine",
  "Riff Raff",
  "Rock and Roll",
  "Rock Around the Clock",
  "Row, Row, Row Your Boat",
  "Runnin' With the Devil",
  "Sabotage",
  "Satanic Slumber Party Part 1 (The Chairman's Portrait)",
  "Satanic Slumber Party Part 2 (Midnight In Sodom)",
  "Satanic Slumber Party Part 3 (Hoof And Horn)",
  "Scared of Christmas",
  "Searching...",
  "Sexual Healing",
  "She'll Be Coming 'Round the Mountain",
  "She's So Fine",
  "Short Change",
  "Should I Stay Or Should I Go",
  "Signed, Sealed, Delivered (I’m Yours)",
  "Singin' In the Rain",
  "Sketches of Brunswick East I",
  "Sketches of Brunswick East II",
  "Sketches of Brunswick East III",
  "Sleep",
  "Smoke & Mirrors",
  "Smoke On the Water",
  "Snow",
  "So Long, Farewell",
  "Space Junk",
  "St. Anger",
  "Stairway to Heaven",
  "Stayin’ Alive",
  "Stella Joy",
  "Steve Nichols",
  "Stevie Ray Horn",
  "Stiff Upper Lip",
  "Streets of Cairo",
  "Summer!",
  "Superposition",
  "Surfin' Safari",
  "Sweet Home Alabama",
  "Sweet Home Chicago",
  "Sweet Talking",
  "Sympathy For The Devil",
  "Taylor",
  "Tea and Jam",
  "Tell the Truth",
  "Tequila",
  "Texas Flood",
  "That's the Way (I Like It)",
  "The 10th Boogie",
  "The Acrid Corpse",
  "The Boss",
  "The End",
  "The Floating Fire",
  "The Funeral",
  "The God Mans Goat Lust",
  "The Grudge",
  "The Killing Ground",
  "The Land Before Timeland",
  "The Last Oasis",
  "The Mother Hen",
  "The Spider and Me",
  "The Star Spangled Banner",
  "Third Stone From The Sun",
  "Thunderstorms",
  "Time = Fate",
  "Time After Time",
  "Timeland",
  "Tomorrow",
  "Torture Chamber",
  "Tribute",
  "Tutti Frutti",
  "Twist",
  "Ugly Guitars",
  "Unknown Legend",
  "Viva Las Vegas",
  "Voodoo Child (Slight Return)",
  "Walk The Dinosaur",
  "Walkin' on the Sun",
  "Way Out West",
  "We Will Rock You",
  "Welcome to the Jungle",
  "Western",
  "What I Do",
  "Whole Lotta Rosie",
  "Work It",
  "Worm",
  "Ya Love",
  "You're Not Naked",
  "Yours",
  "Zebra",
];
